### ISSUE TITLE
PHPStan Latte `$level++`

### ISSUE THREAD

**Issue by spaze** [spaze/michalspacek.cz#141]
The app is running PHPStan on level 8 for quite some time already (5cc25c4aa8d106aaa1755bc1fa70796a6f168806) and now even on level 9 #147, so let's see how far I can bring the Latte extensions.

PHPStan Latte Levels and PRs:

L*nil*:
- #51
- #68

L0:
- #79

L1:
- #71
- #128
- #133

L2:
- #140
- #135

L3:
- #142

L4:
- #171
- efabrica-team/phpstan-latte#387
- efabrica-team/phpstan-latte#388
  I was able to work around the bug by using just one form for both adding something and editing something
- efabrica-team/phpstan-latte#389
- efabrica-team/phpstan-latte#390
- efabrica-team/phpstan-latte#391
- #143
- #180

L5:
- #173
- efabrica-team/phpstan-latte#396
  Worked around it in ff672c9c94d0f3ce214589efe28c34b081c20311

L6:
- #174

L7:
- efabrica-team/phpstan-latte#398
  Workaround in #175
- efabrica-team/phpstan-latte#380
  2 related errors are ignored in #176 2d7735eca379e2cf1a795575ed62a5ce3170bbe8
- #175
- #176

L8:
- #177

L9:
- #179

**Comment by spaze** [comment]
![image](https://github.com/spaze/michalspacek.cz/assets/1966648/8dcc35ea-aec9-43d8-85c0-face53dcdedc)

**Comment by spaze** [comment]
Hey @lulco @MartinMystikJonas look I made it to and past the final boss 🦾

Thanks for creating the extension, looking forward to the next releases. If you want, and think it would be useful, feel free to use this code base for some kind of tests, like regression or so. The license allows it but I wanted to be explicit.

The extension helped me to find some buggy code, like for example that I [had a form component and a form container sharing the same name](https://github.com/spaze/michalspacek.cz/pull/176/commits/9fda4ddb2edeb26d16540d4339be8824b5d78950). It worked but probably just by coincidence.

**Comment by lulco** [comment]
Thanks for using our extension! I wish there were more developers using Nette doing it too. Maybe you can share your experiences O:-)

Ad your error - it is corect to use same name for container and control in it. Extension reports it because of its actual implementation which is hacky. We are trying to improve it step by step.

**Comment by spaze** [comment]
Interesting, having a form container and a field with the same name felt wrong (because of accessing it with `$form[foo]`) even though it worked, probably because the field is inside the container sharing the same name, not on the same level.

Anyway, this was an easy change, unlike some other refactoring (which should have been done much much earlier but I was lazy and didn't have the right tools available).

**Comment by lulco** [comment]
> Interesting, having a form container and a field with the same name felt wrong (because of accessing it with `$form[foo]`)


This is kind of transformation we have done to make forms work with extension. The original compiled template is different. 


> Anyway, this was an easy change, unlike some other refactoring (which should have been done much much earlier but I was lazy and didn't have the right tools available).

**Comment by spaze** [comment]
> This is kind of transformation we have done to make forms work with extension. The original compiled template is different.

Good to know this can also be somehow changed!
