### ISSUE TITLE
Blog post preview in admin throws 500

### ISSUE THREAD

**Issue by spaze** [spaze/michalspacek.cz#169]
`Typed property MichalSpacekCz\Articles\Blog\BlogPost::$edits must not be accessed before initialization`
File: `.../Articles/Blog/BlogPostPreview.php:34`

A regression introduced in #137 commit 18b1d2a7e69fc3e518433fbd57f3aae2940f295c, [here](https://github.com/spaze/michalspacek.cz/commit/18b1d2a7e69fc3e518433fbd57f3aae2940f295c#diff-57926ac4881bcd81040871c0d60f11819b0a174f0615b90d3c247af1dd7ec392L34-R34):
```diff
-		$template->edits = $post->postId ? $this->blogPosts->getEdits($post->postId) : [];
+		$template->edits = $post->postId ? $post->edits : [];
```

**Comment by spaze** [comment]
Reopening, this time it's `Latte\RuntimeException: Missing template file '/srv/www/michalspacek.cz/site/app/Articles/Blog/../Www/Presenters/templates/Post/default.latte'` Caused in #137 and 18b1d2a7e69fc3e518433fbd57f3aae2940f295c as well, by moving the `\MichalSpacekCz\Articles\Blog\BlogPostPreview` service one level down. Or caused by not having tests. Or both.

**Comment by spaze** [comment]
Long time no see. This time it's
```
Nette\InvalidArgumentException: Component with name 'articleHeaderIcons' does not exist. in /srv/www/michalspacek.cz/site/vendor/nette/component-model/src/ComponentModel/Container.php:149  @  https://admin.michalspacek.cz/blog/edit/30
```
Caused in #143, 091eafbb712458e6e6ee30988c41143b6089e329.

**Comment by lulco** [comment]
Are you able to create failing test case? We should found this kind of bugs with phpstan latte

**Comment by spaze** [comment]
I may try to, need to understand the tests structure first though :-)

**Comment by lulco** [comment]
If you will not understand it, just try to describe it to me :) I tried to figure it out from the code, but I can't find the problem myself, because in this presenter templates there is no usage of this control

**Comment by spaze** [comment]
Okay, thanks, I'll try to describe it first and then if you're going to write a test I'll use that as a reference next time.

First things first, this is going to be about the "Component with name 'articleHeaderIcons' does not exist" fixed in #190, I think that's what you're interested in this time, but I wanted to make sure we're on the same page. Maybe the root cause is the same as for "Missing template file" fixed in 7c599314eaff6293ba89a0c0b0eb0707d532e653.

I have a simple & stupid blog where you can write a blog post and click a "Preview" button and it will load the blog post into an iframe. The edit/preview form is created here:
https://github.com/spaze/michalspacek.cz/blob/e1362ca993c04810ab847b597f3eff17edf864e3/site/app/Admin/Presenters/BlogPresenter.php#L54-L68
And this is the "Preview" click handler

https://github.com/spaze/michalspacek.cz/blob/e1362ca993c04810ab847b597f3eff17edf864e3/site/app/Form/PostFormFactory.php#L122-L124

Note the `$template` variable on the last line:
https://github.com/spaze/michalspacek.cz/blob/e1362ca993c04810ab847b597f3eff17edf864e3/site/app/Form/PostFormFactory.php#L124-L124

This is how it's passed to that method in the first code snippet above:
https://github.com/spaze/michalspacek.cz/blob/e1362ca993c04810ab847b597f3eff17edf864e3/site/app/Admin/Presenters/BlogPresenter.php#L68-L68

So we're kind of still in the same presenter where you don't see the `articleHeaderIcons` control anywhere in the according template. Well, that's because it's not there 😅
What I'll do in the `sendPreview()` method is this:
https://github.com/spaze/michalspacek.cz/blob/e1362ca993c04810ab847b597f3eff17edf864e3/site/app/Articles/Blog/BlogPostPreview.php#L29-L32

I'll switch the template file for something else while technically still being in the old presenter.

And then the template response is sent with `\Nette\Application\UI\Presenter::sendTemplate()` here:
https://github.com/spaze/michalspacek.cz/blob/e1362ca993c04810ab847b597f3eff17edf864e3/site/app/Admin/Presenters/BlogPresenter.php#L69-L69

I want the preview to behave exactly like it should, meaning require authentication etc., but look exactly like it would look when viewed. It definitely can be viewed in a different way maybe but here we are 😅

So it could be described as a control that's used in a `setFile()`d template while technically being in the same presenter but the `setFile()` method is called in some other service.

I've realized there's a collector for finding `setFile()` calls but I don't really understand it very well, or at all, right now.

**Comment by lulco** [comment]
Uff 🤪😅
I'm not sure if we can solve this :)) it is little bit complicated O:-)

I have to read this again and again and again :D

but still it is hard to resolve some variables / paths which are set to template if it is sent to some other services etc. We have covered only some simple (štandard / most common) ways :)

**Comment by spaze** [comment]
Yeah, I'll see if I can change it somehow.

**Comment by spaze** [comment]
```
[2023-08-17 00-50-36] PHP Warning: Undefined variable $localeLinks in /srv/www/michalspacek.cz/site/temp/cache/latte/Presenters-templates-@layout.latte--0ded365051.php:159  @  https://admin.michalspacek.cz/blog/edit/78
[2023-08-17 00-50-36] PHP Warning: foreach() argument must be of type array|object, null given in /srv/www/michalspacek.cz/site/temp/cache/latte/Presenters-templates-@layout.latte--0ded365051.php:159  @  https://admin.michalspacek.cz/blog/edit/78
```
Fixed by #200

**Comment by lulco** [comment]
Do you think this could help? https://github.com/efabrica-team/phpstan-latte/issues/424

**Comment by lulco** [comment]
Then maybe this one :) https://github.com/efabrica-team/phpstan-latte/issues/425

But you are right, this is very specific case.

**Comment by spaze** [comment]
Yeah, efabrica-team/phpstan-latte#425 looks more like it.

But I could also add a unit/something test that I think would also help, but I just didn't think/know I need one before I started using PHPStan Latte :-)

**Comment by spaze** [comment]
I've added a unit/integration test in #203 that tests this functionality by just trying to render the template so there should be no more bugs in this part of the app (someone please remind me of this in a year or two).
