### ISSUE TITLE
Migrate away from Font Awesome

### ISSUE THREAD

**Issue by spaze** [spaze/michalspacek.cz#36]
Font Awesome is an awesome font icon collection but
1. requires payment or attribution
2. it's quite a lot of JS/CSS (I extract the icons used to make the size smaller but still)
3. sometimes causes flickering when icons are loaded
4. missing icons are detected too late (no easy static analysis possible)

I should migrate away from it, I quite like @zraly's [Humbleicons](https://humbleicons.com/). They're SVG, can be embedded in HTML & [MIT-licensed](https://github.com/zraly/humbleicons/blob/master/license) (although it's not mentioned on the site itself).

Need to explore whether the Humbleicons collection has all icons I use, or whether there are some viable alternatives. Currently, I use these icons, as extracted with [spaze/fa-extract](https://github.com/spaze/fa-extract):

```
Used icons: array (
  'fas' =>
  array (
    0 => 'asterisk',
    1 => 'bolt',
    2 => 'calendar',
    3 => 'check',
    4 => 'coins',
    5 => 'external-link-square-alt',
    6 => 'flag',
    7 => 'images',
    8 => 'key',
    9 => 'link',
    10 => 'map-marker-alt',
    11 => 'microphone',
    12 => 'moon',
    13 => 'plus',
    14 => 'project-diagram',
    15 => 'rss-square',
    16 => 'sun',
    17 => 'tag',
    18 => 'tags',
    19 => 'times',
    20 => 'video',
    21 => 'wifi',
  ),
  'far' =>
  array (
    0 => 'comment',
    1 => 'comment-alt',
  ),
  'fab' =>
  array (
    0 => 'creative-commons',
    1 => 'creative-commons-by',
  ),
)
```

**Comment by zraly** [comment]
Working on icons you need. For what do you use the icon project-diagram?

**Comment by spaze** [comment]
Wow, that's so nice! Thank you! I haven't had a chance yet to see which ones are available and which not, sorry!

This is where I use the _project-diagram_ icon:
![image](https://user-images.githubusercontent.com/1966648/195408296-fbaa80c0-64d0-4db8-8565-411889fe5743.png)
On my site, on smaller screens, the section of links to other projects of mine is collapsed to s single link. It's supposed to mean "multiple things that are somehow connected and the connection is the me" 😅 I think it can be also replaced with _view-grid_, _view-list_, _dots-horizontal_.

Also, please don't take the `@mention` as "assigning a task" or so, it's more about giving a credit :-) I really like your icon collection and this task is a todo mostly for myself (in case I ever forget the name of the collection, which can happen)

**Comment by spaze** [comment]
Beautiful, thank you! This will take me some time so please don't hold your breath but I'm really looking forward to seeing the icons "live" 🙏
