### ISSUE TITLE
Analyze Latte templates

### ISSUE THREAD

**Issue by spaze** [spaze/michalspacek.cz#51]
Try running PHPStan with https://github.com/efabrica-team/phpstan-latte

If successful, add a composer script and run it on GitHub Actions.

Current blockers:
- [x] https://github.com/efabrica-team/phpstan-latte/pull/132
- [x] A semi-blocker (as I use a service from DIC, I don't load extensions manually) https://github.com/efabrica-team/phpstan-latte/pull/133
- [x] https://github.com/efabrica-team/phpstan-latte/pull/134

**Comment by spaze** [comment]
I'm using callbacks as filters
https://github.com/spaze/michalspacek.cz/blob/766eca5c68d324a213f659a81dc636c27e1321b6/site/app/Templating/TemplateFactory.php#L32-L34

And it seems to be not yet supported:

```
Internal error: Internal error: PHPStan\Reflection\BetterReflection\Reflector\MemoizingReflector::reflectClass(): Argument #1 ($className) must be of type string, MichalSpacekCz\Templating\Filters given, called in michalspacek.cz/site/vendor/efabrica/phpstan-latte/src/VariableCollector/DynamicFilterVariables.php on line 64 in
file michalspacek.cz/site/app/Form/TrainingApplicationPreliminaryFormFactory.php

Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:
#0 michalspacek.cz/site/vendor/efabrica/phpstan-latte/src/VariableCollector/DynamicFilterVariables.php(64): PHPStan\Reflection\BetterReflection\Reflector\MemoizingReflector->reflectClass(Object(MichalSpacekCz\Templating\Filters))
```

Maybe the support will be added in https://github.com/efabrica-team/phpstan-latte/issues/120

**Comment by spaze** [comment]
Current blockers:
- [ ] https://github.com/efabrica-team/phpstan-latte/pull/132
- [ ] A semi-blocker (as I use a service from DIC) https://github.com/efabrica-team/phpstan-latte/pull/133

**Comment by MartinMystikJonas** [comment]
> I'm using callbacks as filters
> 
> https://github.com/spaze/michalspacek.cz/blob/766eca5c68d324a213f659a81dc636c27e1321b6/site/app/Templating/TemplateFactory.php#L32-L34
> 
> And it seems to be not yet supported:
> 
> ```
> Internal error: Internal error: PHPStan\Reflection\BetterReflection\Reflector\MemoizingReflector::reflectClass(): Argument #1 ($className) must be of type string, MichalSpacekCz\Templating\Filters given, called in michalspacek.cz/site/vendor/efabrica/phpstan-latte/src/VariableCollector/DynamicFilterVariables.php on line 64 in
> file michalspacek.cz/site/app/Form/TrainingApplicationPreliminaryFormFactory.php
> 
> Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:
> #0 michalspacek.cz/site/vendor/efabrica/phpstan-latte/src/VariableCollector/DynamicFilterVariables.php(64): PHPStan\Reflection\BetterReflection\Reflector\MemoizingReflector->reflectClass(Object(MichalSpacekCz\Templating\Filters))
> ```
> 
> Maybe the support will be added in [efabrica-team/phpstan-latte#120](https://github.com/efabrica-team/phpstan-latte/issues/120)

Callback filters should be supported. Mentioned error seems like some error with trying to access reflection of unknown class. Could you create issue and post stack trace? I will look at it.

**Comment by MartinMystikJonas** [comment]
Oh I see the problem now. Autodetect of filters from engine do not convert callable [object, method] to correct [class, method] we need later. I will fix it.

**Comment by spaze** [comment]
> Oh I see the problem now. Autodetect of filters from engine do not convert callable [object, method] to correct [class, method] we need later. I will fix it.

Yeah, thank you! :-)

**Comment by lulco** [comment]
Please share with us all of your problems and also success stories. Feedback is welcome.

**Comment by spaze** [comment]
> Please share with us all of your problems and also success stories. Feedback is welcome.

Thank you, I will!

**Comment by lulco** [comment]
Any issue we can help with?

**Comment by spaze** [comment]
I haven't had a chance to look at the news in the extension yet (but hey, I have an excuse: "I'm waiting for a release" 😅) but I see you don't need me 😂

@lulco How did you find https://github.com/efabrica-team/phpstan-latte/issues/191?

**Comment by lulco** [comment]
I forked your branch, because I was curious why it's not working in your CI.

I did some changes and it starts working. So now we will try to fix [these issues](https://github.com/efabrica-team/phpstan-latte/issues/193) and then maybe make some release :)

**Comment by spaze** [comment]
I see, thanks. I think the main reason it's not working is that I required 0.x release 😅 But thanks for looking into it! 👍
